version: '3.8'

services:
  siexan:
    image: ghcr.io/chfischer/siexan:latest
    container_name: siexan-prod
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
